# Generated by Django 5.2.8 on 2025-11-30 06:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backfill_salary_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagdihistory',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='warphistory',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='advance_salary',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_per_saree',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagdihistory',
            name='capacity_sarees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pagdihistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagdi_history', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='salary_rate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='sarees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='week_start',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sareecount',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sareecount',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saree_counts', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='warphistory',
            name='capacity_sarees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='warphistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warp_history', to='core.employee'),
        ),
        migrations.AddIndex(
            model_name='advancehistory',
            index=models.Index(fields=['employee', 'created_at'], name='core_advanc_employe_74bb60_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['phone'], name='core_employ_phone_f66745_idx'),
        ),
        migrations.AddIndex(
            model_name='pagdichangehistory',
            index=models.Index(fields=['employee', 'created_at'], name='core_pagdic_employe_a8b9db_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryhistory',
            index=models.Index(fields=['employee', 'week_start'], name='core_salary_employe_0cbafe_idx'),
        ),
        migrations.AddIndex(
            model_name='sareecount',
            index=models.Index(fields=['employee', 'date'], name='core_sareec_employe_99f97d_idx'),
        ),
    ]
